### PR TITLE
Merge all open pull requests.

### PR DESCRIPTION
**Pull request by SKoschnicke**
Since nothing seems to be happening here for a while and I needed a version with all improvements included, I merged all open PRs in my fork (except the one from @d42f because it is missing tests).

Of course, I only did the merge work, all credit goes to the original contributors for their changes

Feel free to close this PR and merge the original PRs, but maybe someone will find it useful coming here and also needing the improvements merged in one repo.

I am happy to help out with maintaining this project if you need someone, btw. :-)

### CODE REVIEW

**Comment by firehist** [comment]
Hello @SKoschnicke 
First of all, I apologize for this delay, but I didn't had/took the time to take care about this project.
It will change, and I'll take a look at all opening PR.
Thank you very much for your time !
Sorry again for that delay :rocket:

**Comment by SKoschnicke** [comment]
No problem, I'm happy to see that the project will go on. Let me know if you need my help. We are using my fork for some time now and everything seems to work (at least everything we use).

**Comment by firehist** [comment]
Ok. I don't have any rights on the repository, maybe it's time to move it and split it into a more general project like:
- `translation-extractor` (node lib)
- `grunt-translation-extractor` & `gulp-translation-extractor`

With some regex templates (as plugin maybe) to have `angular-translate` and so on.
What do you think about that ?

**Comment by SKoschnicke** [comment]
Makes sense to me, but we should not over-generalize it. Extracting translations from something other than angular will not be required in the near future. But we already have different output formats (YAML and POT), so this should be extensible. I also like your idea to provide separate integrations for grunt and gulp.

**Comment by SKoschnicke** [comment]
So what do you think about three new project as you proposed but renaming `translation-extractor` to `angular-translate-extractor`?

**Comment by firehist** [comment]
Thanks a lot @SKoschnicke and again ... All my excuses :ok_hand:

**Comment by firehist** [comment]
@SKoschnicke 
New repositories will be hosted on https://github.com/Boulangerie which is an organisation to carry our openSource projects (friends & mine).
`angular-translate-extractor`: Node Lib to extract translations
`grunt-angular-translate`: Grunt wrapper
`gulp-angular-translate`: Grunt wrapper

I'll bump grunt package to `1.0.0` once everything will be setup (included travis testing and so on...)

**Comment by SKoschnicke** [comment]
:+1:  Any chance to put information about the move on top of the readme of this repository?

**Comment by firehist** [comment]
Yes, but I just wait that https://github.com/angular-translate/angular-translate-extractor/issues/3 remove the npm package `angular-translate-extractor`.
If no response, I'll refactor `angular-translate-extractor` into `angular-translate-extract` or any other suggestions are welcome :)

**Pull request merged**
